language: python

python: "2.7"

env:
    - TOXENV=py26-d14
    - TOXENV=py26-d15
    - TOXENV=py27-d14
    - TOXENV=py27-d16
    - TOXENV=py33-d15
    - TOXENV=cov

branches:
    only:
        - master
        - develop

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet --use-mirrors coveralls;
        coveralls;
      fi
