language: python

python:
  - 2.7
  - 3.6

env:
  - TOXENV=cov

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-d11

    - python: 3.6
      env: TOXENV=py36-d11
    - python: 3.6
      env: TOXENV=py36-d21

branches:
    only:
        - master
        - develop

install: pip install --quiet tox


script: tox -e ${TOXENV}


after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
